### ISSUE TITLE
Wrong calculation when using big.ZERO

### ISSUE THREAD

**Issue by trading-peter** [sdcoffey/big#5]
When using big.ZERO it seem possible to run into inaccuracy. This example demonstrates it.
Basically all it does is Adding 0.3 and -0.3 which should equate to 0.
When using big.ZERO as the starting base for one of the values the result is inaccurate.

https://play.golang.org/p/XkmYd2j3TdY

**Comment by sdcoffey** [comment]
Thanks for pointing this out! Will check it out asap!

**Comment by sdcoffey** [comment]
I'm not sure why this is, but I've updated the `ZERO` definition to use `NewFromString("0")` under the hood
